apiVersion: v1
kind: ServiceAccount
metadata:
  name: fasttechfoods-kitchen-workload-identity-sa
  namespace: fasttechfoods
  annotations:
    azure.workload.identity/client-id: 9cee9245-db3e-4e10-b008-1759f93cbd8d
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fasttechfoods-kitchen-secrets
  namespace: fasttechfoods
spec:
  provider: azure
  secretObjects:
  - secretName: fasttechfoods-kitchen-api-secrets
    type: Opaque
    data:
    - objectName: SEC-CONNECTION-STRING-DATABASE
      key: CONNECTION_STRING_DATABASE
    - objectName: SEC-JWT-SECRET
      key: JWT_SECRET
    - objectName: SEC-RABBITMQ-CONNECTION-STRING
      key: RABBITMQ_CONNECTION_STRING
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "9cee9245-db3e-4e10-b008-1759f93cbd8d"
    keyvaultName: "kv-hackathon"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: SEC-CONNECTION-STRING-DATABASE
          objectType: secret
          objectVersion: ""
        - |
          objectName: SEC-JWT-SECRET
          objectType: secret
          objectVersion: ""
        - |
          objectName: SEC-RABBITMQ-CONNECTION-STRING
          objectType: secret
          objectVersion: ""
    tenantId: "bda818fe-8a3f-4aa8-88b5-0c0d1976e9f0"
